# Generated by Django 5.2.10 on 2026-01-23 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortune',
            name='message',
            field=models.TextField(unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Fortune Message'),
        ),
    ]
